#!/bin/bash
# This script modifies /etc/hosts
# It sets localhost to 127.0.0.2 and facebook.com to 8.8.8.8

# Create a backup
cp /etc/hosts /etc/hosts.bak

sed -i '/localhost/d' /etc/hosts
sed -i '/facebook.com/d' /etc/hosts

echo "127.0.0.2   localhost" >> /etc/hosts
echo "8.8.8.8     facebook.com" >> /etc/hosts
