#!/usr/bin/env bash
# This script modifies /etc/hosts
# It sets localhost to 127.0.0.2 and facebook.com to 8.8.8.8

sudo sed -i '/127.0.0.2 localhost/d' /etc/hosts
sudo sed -i '/8.8.8.8 facebook.com/d' /etc/hosts
